export const initiativeData = [
  { Project: "CAMPA", City: "Bangalore", Funding: 30 },
  { Project: "Lake Rejuvenation", City: "Bangalore", Funding: 250 },
  { Project: "Solar Power Integration", City: "Bangalore", Funding: 720 },
  { Project: "Community Forest Management", City: "Bangalore", Funding: 85 },
  { Project: "River Cleaning Initiative", City: "Bangalore", Funding: 110 },
  { Project: "Sustainable Urban Agriculture", City: "Bangalore", Funding: 60 },
  { Project: "Smart Water Management System", City: "Bangalore", Funding: 150 },
  { Project: "Green Technology Incubator", City: "Bangalore", Funding: 75 },
  {
    Project: "Eco-friendly Public Transportation",
    City: "Bangalore",
    Funding: 500,
  },
  {
    Project: "Urban Biodiversity Conservation",
    City: "Bangalore",
    Funding: 95,
  },
  { Project: "Tamil Nadu Green Climate Fund", City: "Chennai", Funding: 1000 },
  { Project: "Air Quality Monitoring Network", City: "Chennai", Funding: 130 },
  {
    Project: "Bicycle Infrastructure Development",
    City: "Chennai",
    Funding: 90,
  },
  { Project: "Green Roof Initiative", City: "Chennai", Funding: 55 },
  { Project: "Plastic Waste Reduction Program", City: "Chennai", Funding: 35 },
  { Project: "Coastal Conservation Project", City: "Chennai", Funding: 200 },
  { Project: "Sustainable Housing Project", City: "Chennai", Funding: 400 },
  { Project: "River Restoration Program", City: "Chennai", Funding: 180 },
  { Project: "Green Technology Research Center", City: "Chennai", Funding: 70 },
  { Project: "Urban Forest Park Development", City: "Chennai", Funding: 120 },
  { Project: "Riverfront Restoration", City: "Delhi", Funding: 850 },
  {
    Project: "Green Building Certification Program",
    City: "Delhi",
    Funding: 550,
  },
  { Project: "E-Waste Recycling Center", City: "Delhi", Funding: 160 },
  { Project: "Renewable Energy Microgrid", City: "Delhi", Funding: 280 },
  { Project: "Electric Vehicle Infrastructure", City: "Delhi", Funding: 300 },
  { Project: "Sustainable Tourism Promotion", City: "Delhi", Funding: 95 },
  { Project: "Waterfront Promenade Construction", City: "Delhi", Funding: 200 },
  { Project: "Air Pollution Control Measures", City: "Delhi", Funding: 400 },
  { Project: "Smart City Waste Management", City: "Delhi", Funding: 180 },
  { Project: "Climate-Resilient Infrastructure", City: "Delhi", Funding: 750 },
  {
    Project: "Community-Led Solid Waste Management",
    City: "Lucknow",
    Funding: 100,
  },
  { Project: "Green Corridor Development", City: "Lucknow", Funding: 80 },
  { Project: "Eco-friendly Public Parks", City: "Lucknow", Funding: 45 },
  {
    Project: "Riverfront Beautification Project",
    City: "Lucknow",
    Funding: 120,
  },
  {
    Project: "Affordable Green Housing Initiative",
    City: "Lucknow",
    Funding: 300,
  },
  { Project: "Tree Plantation Drive", City: "Lucknow", Funding: 30 },
  { Project: "Urban Wetland Conservation", City: "Lucknow", Funding: 120 },
  {
    Project: "River Beautification and Cleaning",
    City: "Lucknow",
    Funding: 150,
  },
  {
    Project: "Sustainable Agriculture Promotion",
    City: "Lucknow",
    Funding: 70,
  },
  { Project: "Stormwater Drainage Improvement", City: "Lucknow", Funding: 90 },
  {
    Project: "Smart City Sustainable Transportation",
    City: "Mumbai",
    Funding: 1000,
  },
  { Project: "Rooftop Rainwater Harvesting", City: "Mumbai", Funding: 40 },
  { Project: "Coastal Erosion Mitigation", City: "Mumbai", Funding: 500 },
  { Project: "Green Roof Initiative", City: "Mumbai", Funding: 65 },
  { Project: "Marine Biodiversity Conservation", City: "Mumbai", Funding: 150 },
  {
    Project: "Sustainable Tourism Infrastructure",
    City: "Mumbai",
    Funding: 180,
  },
  { Project: "Urban Tree Canopy Expansion", City: "Mumbai", Funding: 75 },
  {
    Project: "Air Quality Improvement Initiatives",
    City: "Mumbai",
    Funding: 300,
  },
  { Project: "Urban Green Spaces Development", City: "Mumbai", Funding: 120 },
  { Project: "Public Bicycle Sharing Program", City: "Mumbai", Funding: 50 },
];
